app/urls.py
from django.contrib import admin
from django.urls import path
from app import views


app_name='app'

urlpatterns = [
            path('upload/',views.upload_view.as_view(),name='Upld'),
            path('jira_load/',views.jira_load_view.as_view(),name='jira_load'),
            path('release/',views.ReleaseListView.as_view(),name='release_list'),
            path('release/<release>/',views.ReleaseObjectListView.as_view(),name='release_objects'),
            path('release/<release>/Overview',views.rel_overview.as_view(),name='release_overview'),
            path('release/<release>/impplan',views.imp_plan.as_view(),name='imp_plan'),
            path('release/<release>/update_from_jira',views.update_release_items,name='upd_from_jira'),
            path('release/<release>/<pk>/update_from_bitbucket',views.update_bitbucket_files,name='upd_from_bitbucket'),
            path('release/<release_plan>/impplan/pdf',views.render_pdf_view,name='imp_pdf'),
            path('release/<release>/pdf',views.render_pdf_view,name='pdf'),
            path('release/<release>/rel_notes',views.rel_notes_listview.as_view(),name='notes'),
            path('release/<release>/<pk>',views.ReleaseObjectDetailView.as_view(),name='object'),
            path('release/<release>/<pk>/update',views.wmobject_detail_update.as_view(),name='update'),
            path('release/<release>/<pk>/update_from_jira',views.update_item,name='update_from_jira'),
            path('release/<release>/<pk>/attach',views.wmobject_attach_update.as_view(),name='update_attach'),
            path('release/<release>/<pk>/relnot',views.rel_notes_view.as_view(),name='rel_notes'),
            path('test/',views.my_test_view,name='test'),
            path('auth/',views.test_view,name='auth'),
]

dev_easy/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home ,about
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls'),name='app'),
    path('',home,name='home'),
    path('about/',about,name='about'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='home'),name='logout'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/imp_plan.html
{% extends "base.html" %}
{% load filters %}
{% block heading %}
{{Rel}} - Objects List
{% endblock %}
{% block toolbar %}
<a name="" id="" class="btn btn-primary  btn-sm mx-1" href=# role="button">Get Driver File</a>
<a name="" id="" class="btn btn-warning  btn-sm mx-1" href={% url 'app:imp_pdf' Rel %} role="button">Download</a>
<a name="" id="" class="btn btn-warning  btn-sm  %}" href={% url 'app:release_objects' Rel %} role="button">Back</a>
{% endblock %}
{% block content %}
<div class="d-flex overflow-auto">
    <ul class="list-group mb-2">
        {% for head,objs in cont.items %}    
            <li class="list-group-item list-group-item-action py-0" style="background-color:#9a8c98;color:white">{{head}}</li>
            {% comment %} {{objs}} {% endcomment %}
            <table class="table table-hover table-bordered p-0 mb-1">        
                <tr>
                    <th class="h6 py-0 my-0">S.No</th>
                    <th class="h6 py-0 my-0">Track</th>                    
                    <th class="h6 py-0 my-0">CR# / US#</th>
                    <th class="h6 py-0 my-0">Status</th>
                    <th class="h6 py-0 my-0">Pre-Req Task</th>
                    <th class="h6 py-0 my-0">Seq#</th>
                    <th class="h6 py-0 my-0">P4V Location</th>
                    <th class="h6 py-0 my-0">Object File Name</th>
                    <th class="h6 py-0 my-0">Version#</th>
                    <th class="h6 py-0 my-0">Execution Schema</th>
                    <th class="h6 py-0 my-0">Object Name</th>
                    <th class="h6 py-0 my-0">Comments</th>
                    <th class="h6 py-0 my-0">Special Instructions</th>
                    <th class="h6 py-0 my-0">Backout Instructions</th>
                    <th class="h6 py-0 my-0">DB Instances (For Dev / UAT)</th>
                    <th class="h6 py-0 my-0">Requestor</th>                    
                </tr>
                {% for obj in objs %}
                <tr>
                    <td class="h6 py-0 my-0"></td>
                    <td class="h6 py-0 my-0">{{obj.fk_wmobject.object_track}}</td>                    
                    <td class="h6 py-0 my-0">{{obj.fk_wmobject.object_id}}</td>
                    <td class="h6 py-0 my-0"></td>
                    <td class="h6 py-0 my-0"></td>
                    <td class="h6 py-0 my-0">{{ forloop.counter }}</td>
                    <td class="h6 py-0 my-0">{{obj.object_path|lsplit:0}}</td>
                    <td class="h6 py-0 my-0">{{obj.object_path|lsplit:1}}</td>
                    <td class="h6 py-0 my-0">Latest</td>
                    <td class="h6 py-0 my-0">Prod</td>
                    <td class="h6 py-0 my-0"></td>
                    <td class="h6 py-0 my-0">{{obj.object_comment}}</td>
                    <td class="h6 py-0 my-0"></td>
                    <td class="h6 py-0 my-0">{{obj.object_backout}}</td>
                    <td class="h6 py-0 my-0">EBIZDEV/EBIZQA</td>
                    <td class="h6 py-0 my-0">{{obj.fk_wmobject.object_dev}}</td>
                </tr>        
                {% endfor %}
            </table>
        {% endfor %}
    </ul>
</div>


{% endblock content %}

app/templates/imp_plan_print.html
{% extends "base_print.html" %}
{% load filters %}

{% block style %}
    @page {
    size: A2 landscape;
    margin: 1cm;
}
{% endblock %}


{% block heading %}
<div style="text-align:center">
    {{Rel}} - Implementation Plan
</div>
{% endblock %}

{% block content %}
<div >
    <ul >
        {% for head,objs in cont.items %}    
            <li  style="background-color:#9a8c98;color:white;width:auto;">{{head}}</li>
            {% comment %} {{objs}} {% endcomment %}
            <table style="border: 1px solid black;width:auto;">        
                <tr style="text-align:center; width:auto;">
                    <th style="width:50px;">S.No</th>
                    <th style="width:100px">Track</th>
                    <th style="width:100px">CR# / US#</th>
                    <th style="width:100px">Status</th>
                    <th style="width:50px">Pre-Req Task</th>
                    <th style="width:50px">Seq#</th>
                    <th style="width:auto" >P4V Location</th>
                    <th style="width:auto">Object Name</th>
                    <th style="width:100px">Version#</th>
                    <th style="width:100px">Execution Schema</th>
                    <th style="width:100px">Object Name</th>
                    <th style="width:auto">Comments</th>
                    <th style="width:auto">Special Instructions</th>
                    <th style="width:auto">Backout Instructions</th>
                    <th style="width:100px">DB Instances (For Dev / UAT)</th>
                    <th style="width:100px">Requestor</th>                    
                </tr>
                {% for obj in objs %}
                <tr style="text-align:center;width:auto;">
                    <td style="padding-top: 3px;" >{{seq_cnt}}</td>
                    <td style="padding-top: 3px;" >{{obj.fk_wmobject.object_track}}</td>                    
                    <td style="padding-top: 3px;" >{{obj.fk_wmobject.object_id}}</td>
                    <td style="padding-top: 3px;" ></td>
                    <td style="padding-top: 3px;" ></td>
                    <td style="padding-top: 3px;" >{{ forloop.counter }}</td>
                    <td style="padding-top: 3px;" >{{obj.object_path|lsplit:0}}</td>
                    <td style="padding-top: 3px;" >{{obj.object_path|lsplit:1}}</td>
                    <td style="padding-top: 3px;" >Latest</td>
                    <td style="padding-top: 3px;" >Prod</td>
                    <td style="padding-top: 3px;" ></td>
                    <td style="padding-top: 3px;" >{{obj.object_comment}}</td>
                    <td style="padding-top: 3px;" ></td>
                    <td style="padding-top: 3px;" >{{obj.object_backout}}</td>
                    <td style="padding-top: 3px;" >EBIZDEV/EBIZQA</td>
                    <td style="padding-top: 3px;" >{{obj.fk_wmobject.object_dev}}</td>
                </tr>        
                {% endfor %}
            </table>
        {% endfor %}
    </ul>
</div>


{% endblock content %}

app/templates/jira_load.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Jira Pull
{% endblock title %}

{% block heading %}
<div class="text-center">
  Objects from Jira Projects
</div>

{% endblock heading %}

{% block toolbar %}
<a name="" id="" class="btn btn-warning btn-sm" href={% url 'app:release_list' %} role="button">Back</a>
{% endblock toolbar %}


{% block content %}
<div class="container">
  <form method="post" enctype="multipart/form-data" class="form-group">
    {% csrf_token %}
    
    <div class="input-group m-1">
    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon1">Project Code</span>
    </div>
    <input type="text" class="form-control" name="project_name" placeholder="Project Code" aria-label="Project Code" aria-describedby="basic-addon1">
  </div>

    <div class="input-group m-1">
    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon1">Fix Version</span>
    </div>
    <input type="text" class="form-control" name="fix_version" placeholder="Fix Version" aria-label="Fix Version" aria-describedby="basic-addon1">
  </div>
    <button type="submit"  class="btn btn-sm btn-primary m-1">Pull</button>
  </form>
<br>
  {{message}}  
</div>

{% endblock %}

app/templates/object_detail.html
{% extends "base.html" %}
{% block heading %}
<span class="badge badge-info">{{object.object_type}}</span>
{{object.object_id}} - {{object.object_desc}}
  
<br>
<div class="text-right">
Dev - {{object.object_dev}}
QA- {{object.object_qa}}     
</div>
{% endblock heading %}

{% block toolbar %}
    <a name="" id="" class="btn btn-primary mx-1 btn-sm d-inline" href={% url 'app:update_from_jira' object.object_rel object.object_id %} role="button">Update from Jira</a>
    <a name="" id="" class="btn btn-warning mx-1 btn-sm d-inline" href={% url 'app:rel_notes' object.object_rel object.object_id %} role="button">Release Note</a>
    <a name="" id="" class="btn btn-warning mx-1 btn-sm d-inline" href={% url 'app:release_objects' object.object_rel %} role="button">Back</a>    
{% endblock toolbar %}

{% block content %}
<div class="my-1">
    <h5 class="d-inline ">Overview</h5>
    
    <ul class="list-group d-flex-inline flex-nowrap list-group-horizontal ">
    {% for rec in res  %}                
        <li class="list-group-item d-flex justify-content-between align-items-center py-1 ">
            {{rec.object_type__lookup_desc}}
        <span class="badge badge-primary badge-pill ml-2">{{rec.cnt}}</span>
        </li>
    {% endfor %}
    </ul>
</div>



<div class="my-1 d-flex justify-content-between">
    <h5 class="d-inline mb-2">Objects</h5>
    <div class="my-1 d-flex justify-content-right">
    <a name="" id="" class="btn btn-primary mx-1 btn-sm d-inline" href={% url 'app:upd_from_bitbucket' object.object_rel object.object_id %} role="button">Pull from Bitbucket</a>
    <a name="" id="" class="btn btn-warning btn-sm d-inline" href={% url 'app:update'  object.object_rel object.object_id %} role="button">Edit</a>  
    </div>
</div>
<table class="table table-hover table-bordered ">
    <thead class="text-light " style="background-color:#14213D">
            <tr>
                <th class="pt-0 pb-0" >Type</th>
                <th class="pt-0 pb-0">Path</th>
                <th class="pt-0 pb-0">Backout</th>
                <th class="pt-0 pb-0">Special</th>
                <th class="pt-0 pb-0">Comments</th>
            </tr>
        </thead>
        <tbody>
            {% for dtl in dtls %}
            <tr >
                <td class="pt-0 pb-0">{{dtl.object_type}}</td>
                <td class="pt-0 pb-0">{{dtl.object_path}}</td>
                <td class="pt-0 pb-0">{{dtl.object_backout}}</td>
                <td class="pt-0 pb-0">{{dtl.object_special}}</td>
                <td class="pt-0 pb-0">{{dtl.object_comment}}</td>
            </tr>
            {% endfor %} 
        </tbody>
</table>

<div class="my-1 d-flex justify-content-between">
    <h5 class="d-inline mb-2">Attachments</h5>
    <a name="" id="" class="btn btn-warning btn-sm d-inline" href={% url 'app:update_attach'  object.object_rel object.object_id %} role="button">Edit</a>  
</div>
   
<table class="table table-hover table-bordered ">
    <thead style="background-color:#14213D" class="text-light">
            <tr>
                <th class="py-0" >AttachType</th>
                <th class="py-0">Attachment</th>
            </tr>        
        </thead>
        <tbody>
        <div>
            {% for att in attach %}
            <tr >
                <td class="pt-0 pb-0">{{att.attach_type}}</td>
                <td class="pt-0 pb-0">{{att.attach_file}}</td>
            </tr>
            {% endfor %} 
        </div>
        </tbody>
</table>

{% endblock content %}

app/templates/rel_notes.html
{% extends "base.html" %}
{% block heading %}
{{Rel}} - Release Notes
{% endblock heading%}
{% block toolbar %}
<a name="" id="" class="btn btn-warning btn-sm mx-1" href={% url 'app:pdf' Rel %} role="button">Download</a>
<a name="" id="" class="btn btn-warning btn-sm " href={% url 'app:release_objects' Rel %} role="button">Back</a>
{% endblock %}
{% block content %}
<ul class="list-group my-1">
    {% for obj in release_objects %}   

        <li class="list-group-item list-group-item-action p-0 m-0">
            <table class="table table-bordered" >
                <tr class="d-flex" style="background-color:#14213D;color:white" >
                    <td class="col-2 " >
                        {{obj.fk_wmobject.object_id}}
                    </td>
                    <td class="col "  >
                        {{obj.fk_wmobject.object_desc}}
                    </td>
                </tr>
                <tr class="d-flex">
                    <td class="col-2">
                        Application Impact
                    </td>
                    <td class="col-10">
                        {{obj.app_imp}}
                    </td>
                </tr>
                <tr class="d-flex">
                    <td class="col-2">
                        Process Impact
                    </td>
                    <td class="col-10" >
                        {{obj.proc_imp}}
                    </td>
                </tr>
                <tr class="d-flex">
                    <td class="col-2">
                        Objective
                    </td>
                    <td class="col-10" >
                        {{obj.objective}}
                    </td>
                </tr>
                <tr class="d-flex">
                    <td class="col-2">
                        Resolution
                    </td>
                    <td class="col-10"  >
                        {{obj.resolution}}
                    </td>
                </tr>
                <tr class="d-flex">
                    <td class="col-2 " >
                        Screen
                    </td>
                    <td class="col-10" >
                        {% if obj.img1 %}
                            <img src={{obj.img1.url}} alt="Image Not Found" class="img-thumbnail">
                        {% endif %}
                        {% if obj.img2 %}                    
                            <img src={{obj.img2.url}}  class="img-thumbnail">
                        {% endif %}
                        {% if obj.img3 %}                    
                            <img src={{ obj.img3.url }} alt="" class="img-thumbnail">
                        {% endif %}
    
                    </td>
                </tr>
        </table>
        </li>
        <br>

    {% endfor %}
</ul>

{% endblock content %}

app/templates/rel_notes_print.html
{% extends "base_print.html" %}
{% block heading %}



{{Rel}} - Release Notes
{% endblock heading%}

{% block content %}
    {% for obj in release_objects %}   
        <table class="table table-bordered" style="border: 1px solid black;">
            <tr style="width:auto">
                <td  style="background-color:#C2C2C2;padding:3px;">
                    {{obj.fk_wmobject.object_id}}
                </td>
                <td  style="background-color:#C2C2C2;padding:3px;" >
                    {{obj.fk_wmobject.object_desc}}
                </td>
            </tr>
            <tr style="width:auto">
                <td style="padding:3px;width:150px">
                    Application Impact
                </td>
                <td  style="padding:3px;width:800px">
                    {{obj.app_imp}}
                </td>
            </tr>
            <tr style="width:auto">
                <td style="padding:3px;width:150px">
                    Process Impact
                </td>
                <td  style="padding:3px;width:800px">
                    {{obj.proc_imp}}
                </td>
            </tr>
            <tr style="width:auto">
                <td style="padding:3px;width:150px">
                    Objective
                </td>
                <td  style="padding:3px;width:800px">
                    {{obj.objective}}
                </td>
            </tr>
            <tr style="width:auto">
                <td style="padding:3px;width:150px">
                    Resolution
                </td>
                <td  style="padding:3px;width:800px">
                    {{obj.resolution}}
                </td>
            </tr>
            {% if obj.img1 %}
            <tr style="width:auto">
                <td style="vertical-align: top;padding: 3px;width:150px">
                    Screen
                </td>
                <td  style="width:800px" >                        
                    <img src={{obj.img1.url}} alt="Image Not Found" class="img-thumbnail">
                </td>
            </tr>
            {% endif %}
            {% if obj.img2 %}
            <tr style="width:auto">
                <td  style="vertical-align: top;padding:3px;width:150px">
                    Screen
                </td>
                <td  style="width:800px" >                        
                    <img src={{obj.img2.url}} alt="Image Not Found" class="img-thumbnail">
                </td>
            </tr>
            {% endif %}
            {% if obj.img3 %}
            <tr style="width:auto">
                <td  style="vertical-align: top;padding:3px;width:150px">
                    Screen
                </td>
                <td style="width:800px">                        
                    <img src={{obj.img3.url}} alt="Image Not Found" class="img-thumbnail">
                </td>
            </tr>
            {% endif %}   
    </table>
    <br>

    {% endfor %}
{% endblock content %}

app/templates/release_list.html
{% extends "base.html" %}

{% block title %}
Release List
{% endblock title %}


{% block heading %}
<div class="text-center">
    Release List
</div>
{% endblock heading %}

{% block toolbar %}
 <a name="" id="" class="btn btn-primary btn-sm mx-1" href={% url 'app:jira_load'  %} role="button">Jira</a>
 {% comment %} <a name="" id="" class="btn btn-primary btn-sm mx-1" href={% url 'app:Upld'  %} role="button">Upload</a> {% endcomment %}
 <a name="" id="" class="btn btn-warning btn-sm mx-1" href={% url 'home' %} role="button">Back</a>
{% endblock toolbar %}

{% block content %}
    <ul class="list-group" >
        {% for rel in release_list %}    
            <li class="list-group-item list-group-item-action py-1"><a href={% url 'app:release_objects' rel.object_rel %}>{{rel.object_rel}}</a></li>
        {% endfor %}
    </ul>
    
{% endblock content %}

app/templates/release_objects.html
{% extends "base.html" %}
{% block heading %}
<div class="row justify-content-center">
    {{Rel}} - Objects List
</div>
{% endblock heading %}

{% block toolbar %}
    {% comment %} <a name="" id="" class="btn btn-primary d-inline btn-sm mx-1" href={% url 'app:upd_from_jira' Rel %} role="button">Pull from Jira</a> {% endcomment %}
    <a name="" id="" class="btn btn-warning d-inline btn-sm mx-1" href={% url 'app:release_overview' Rel %} role="button">Overview</a>
    <a name="" id="" class="btn btn-warning d-inline btn-sm mx-1" href={% url 'app:notes' Rel %} role="button">Rel Notes</a>
    <a name="" id="" class="btn btn-warning d-inline btn-sm mx-1" href={% url 'app:imp_plan' Rel %} role="button">Impl Plan</a>
    <a name="" id="" class="btn btn-warning d-inline btn-sm mx-1" href={% url 'app:release_list'  %} role="button">Back</a>
{% endblock toolbar %}

{% block content %}

    <ul class="list-group mb-2">
        {% for obj in release_objects %}    
            <li class="list-group-item list-group-item-action py-0 mt-0 mb-0"><a href={% url 'app:object'  obj.object_rel obj.object_id %} >{{obj}}</a></li>
        {% endfor %}
    </ul>


{% endblock content %}

app/templates/release_overview.html
{% extends "base.html" %}
{% block heading %}
    {{rel}} - Overview
{% endblock heading %}

{% block toolbar %}
    <a name="" id="" class="btn btn-warning btn-sm" href={% url 'app:release_objects' rel %} role="button">Back</a>
{% endblock toolbar %}
{% block content %}    
    <div class ="row">
    <div class ="col-2">
    <ul class="list-group mb-2 ">
        {% for us in usde  %}                
            <li class="list-group-item d-flex justify-content-between align-items-center " >
                {{us.object_type}}
            <span class="badge badge-danger  justify-content-right">{{us.cnt}}
            </span>                
            </li>
        {% endfor %}
            <li class="list-group-item d-flex justify-content-between align-items-center " >
                Merge
            <span class="badge badge-danger  justify-content-right">{{merg.cnt__count}}
            </span>                
            </li>
        </ul>
    <ul class="list-group">
    {% for rec in res  %}                
        <li class="list-group-item d-flex justify-content-between align-items-center ">
            {{rec.object_type__lookup_desc}}
        <span class="badge badge-success  justify-content-right">{{rec.tot}} </span>
        </li>
    {% endfor %}

    </ul>
    </div>

    <div class ="col-10">    
        <table class="table table-bordered">
            <tbody>
                {% for obj in objs  %}  
                {% if obj.cnt > 1%}
                <tr class="bg-info">
                {%else%}
                <tr>
                {% endif %}
                    <td class="py-0 my-0">{{obj.object_type__lookup_desc}}</td>
                    <td class="py-0 my-0">{{obj.object_path}}</td>
                    <td class="py-0 my-0">{{obj.cnt}}</td>
                    <td class="py-0 my-0">{{obj.fk_wmobject__object_id}}</td>
                </tr>
                {% endfor %}
            </tbody>                
        </table>
    </div>
    </div>

{% endblock %}

app/templates/test.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>'File Upload'</title>
{% endblock title %}

{% block content %}
<h1>This is test page</h1>
{% endblock content %}

app/templates/upload.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Upload
{% endblock title %}

{% block heading %}
<div class="text-center">
  Release Objects Upload
</div>

{% endblock heading %}

{% block toolbar %}
<a name="" id="" class="btn btn-warning btn-sm" href={% url 'app:release_list' %} role="button">Back</a>
{% endblock toolbar %}


{% block content %}
<div class="container">
  <form method="post" enctype="multipart/form-data" class="form-group">
    {% csrf_token %}
    <div class="input-group mb-1">
    <input type="file" name="file" class="form-control p-1" required>
    </div>
    <button type="submit"  class="btn btn-sm btn-primary m-1">Upload</button>
  </form>
<br>
  {{message}}  
</div>

{% endblock %}

app/templates/wmobject_rel_notes.html
{% extends "base.html" %}
{% block heading %}
{{obj.object_id}} - {{obj.object_desc}}
{{obj.object_rel}}
{% endblock heading %}

{% block toolbar %}
    <a name="" id="" class="btn btn-warning btn-sm" href={% url 'app:object' obj.object_rel obj.object_id %} role="button">Back</a>
{% endblock  %}

{% block content %}


<div class="row">
    <div class="col">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
                {{formset.as_p}}
            <input class="btn btn-primary my-1 btn-sm d-inline" type="submit" value="Save">
            </form>        
    </div>
    
    <div class="col">
        <h5>Preview</h5>
        <table class="table table-bordered">
            <tr>
                <td>
                    {{prev.app_imp}}
                </td>
            </tr>
            <tr>
                <td>
                    {{prev.proc_imp}}
                </td>
            </tr>
            <tr>
                <td>
                    {{prev.objective}}
                </td>
            </tr>
            <tr>
                <td>
                    {{prev.resolution}}
                </td>
            </tr>
            {% if prev.img1 %}
            <tr>
                <td>
                    <img src={{prev.img1.url}} alt="Image Not Found" class="img-thumbnail">
                </td>
            </tr>
            {% endif %}
            {% if prev.img2 %}
            <tr>
                <td>
                    <img src={{prev.img2.url}}  class="img-thumbnail">
                </td>
            </tr>
            {% endif %}
            {% if prev.img3 %}
            <tr>
                <td>
                    <img src={{ prev.img3.url }} alt="" class="img-thumbnail">
                </td>
            </tr>
            {% endif %}
        </table>
    </div>    
</div>

{% endblock content %}

app/templates/wmobject_update.html
{% extends "base.html" %}
{% block heading %}
    {{obj.object_id}} - {{obj.object_desc}}
    {{obj.object_rel}}
{% endblock heading %}

{% block toolbar%}
    <a name="" id="" class="btn btn-warning btn-sm " href={% url 'app:object' obj.object_rel obj.object_id %} role="button">Back</a>
{% endblock%}

{% block content %}
<form method="post">
{% csrf_token %}
{{ formset.management_form }}
<input class="btn btn-primary my-1 btn-sm d-inline" type="submit" value="Save">
<input class="btn btn-success my-1 btn-sm d-inline" type="button" onclick='check("test")' value="Add">
<table  id="frmset" class="table table-hover table-bordered mb-2">
    <thead class="thead-dark">
        <tr >
            <th class="px-0 py-0 ">Type</th>
            <th class="px-0 py-0 ">Object Path</th>
            <th class="px-0 py-0 ">Object Backout</th>
            <th class="px-0 py-0 ">Special</th>
            <th class="px-0 py-0 ">Comments</th>
            <th class="px-0 py-0 ">Delete</th>
        </tr>
        </thead>
        <tbody>
            {% for frm in formset %}
            {{ frm.id }}
                <tr > 
                    <td class="px-0 py-0">{{frm.object_type}}</td>
                    <td class="px-0 py-0">{{frm.object_path}}</td>
                    <td class="px-0 py-0">{{frm.object_backout}}</td>
                    <td class="px-0 py-0">{{frm.object_special}}</td>
                    <td class="px-0 py-0">{{frm.object_comment}}</td> 
                    <td class="px-0 py-0">{% if formset.can_delete %}
                            {{ frm.DELETE }}
                    {% endif %}</td>
                </tr>
            {% endfor %}
        </tbody>
</table>

<table id='empty_form' style="display: None;">
    <td class="px-0 py-0">{{formset.empty_form.object_type}}</td>
    <td class="px-0 py-0">{{formset.empty_form.object_path}}</td>
    <td class="px-0 py-0">{{formset.empty_form.object_backout}}</td>
    <td class="px-0 py-0">{{formset.empty_form.object_special}}</td>
    <td class="px-0 py-0">{{formset.empty_form.object_comment}}</td> 
    <td class="px-0 py-0">{% if formset.can_delete %}
            {{ formset.empty_form.DELETE }}
    {% endif %}</td>
</table>


</form>


<script>
    function check(par) {
        var cnt = $("#id_form-TOTAL_FORMS").val();
        //console.log($("#frmset").html());
        var new_frm = $("#empty_form").html().replace(/__prefix__/g,cnt);
        $("#frmset").append(new_frm);
        $("#id_form-TOTAL_FORMS").val(parseInt(cnt)+1)
        console.log($("#id_form-TOTAL_FORMS").val())
    }
</script>

{% endblock content %}

app/templates/wmobject_update_all.html
{% extends "base.html" %}


{% block content %}
<form method="post">
{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{% endblock content %}